# Generated by Django 3.0 on 2020-01-13 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название рубрики')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TorrentClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('qBittorrent', 'qBittorrent'), ('uTorrent', 'uTorrent')], max_length=300, verbose_name='Торрент клиент')),
                ('host', models.CharField(blank=True, max_length=300, verbose_name='Хост')),
                ('port', models.IntegerField(default=8080, verbose_name='Порт')),
                ('login', models.CharField(blank=True, max_length=300, verbose_name='Логин')),
                ('password', models.CharField(blank=True, max_length=300, verbose_name='Пароль')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_shared_cards', models.BooleanField(default=False, verbose_name='Показывать и загружать карточки других авторов, у которых разрешен просмотр всем')),
                ('t_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.TorrentClient', verbose_name='Торрент клинет')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1000, verbose_name='Название')),
                ('short_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Сокращение')),
                ('use_short_name', models.BooleanField(default=True, verbose_name='Использовать поле "Сокращение" для отображения на глвной')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='комментарий/заметка')),
                ('size', models.CharField(max_length=20, null=True, verbose_name='Размер')),
                ('date_upd', models.DateTimeField(db_index=True, verbose_name='Дата последнего обновления')),
                ('img_url', models.CharField(max_length=300, verbose_name='URL картинки')),
                ('url', models.CharField(blank=True, max_length=300, null=True, verbose_name='url торрена на ресурсе загрузки')),
                ('magnet_url', models.CharField(blank=True, max_length=300, null=True, verbose_name='магнет url')),
                ('torrent_url', models.CharField(blank=True, max_length=300, null=True, verbose_name='торрент url')),
                ('is_new_data', models.BooleanField(default=False, help_text='<em class="text-white">При загрузке обновленных карточек будет загружена</em>', verbose_name='Доступны обновления.')),
                ('is_view', models.BooleanField(default=False, verbose_name='Разрешить просмотр всем пользователям')),
                ('is_edit', models.BooleanField(default=False, verbose_name='Разрешить редактирование и удаление всем пользователям.')),
                ('plugin_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Добавлено через плагин')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rubric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Rubric', to_field='name', verbose_name='Рубрика')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TorrentTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Rutracker', 'Rutracker')], max_length=300, verbose_name='Торрент-трекер')),
                ('session', models.CharField(blank=True, max_length=500, verbose_name='session')),
                ('login', models.CharField(blank=True, max_length=200, verbose_name='Логин')),
                ('password', models.CharField(blank=True, max_length=200, verbose_name='Пароль')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
