# Generated by Django 3.0.4 on 2020-04-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, verbose_name='uuid'),
        ),
        migrations.AlterField(
            model_name='torrenttracker',
            name='name',
            field=models.CharField(choices=[('Kinozal_tv', 'Kinozal_tv'), ('Lostfilm_tv', 'Lostfilm_tv'), ('Rutracker', 'Rutracker')], max_length=300, verbose_name='Торрент-трекер'),
        ),
    ]
